### ISSUE TITLE
Добавление bemto

### ISSUE THREAD

**Issue by andrew--r** [straykov/initium#22]
Ребят, не задумывались подключить [bemto](https://github.com/kizu/bemto), чтобы разметку БЭМ-блоков удобнее было фигачить?

**Comment by straykov** [comment]
Чё-то надо подумать сначала

**Comment by Krekotun** [comment]
Проблемы с pug есть, вроде

**Comment by andrew--r** [comment]
И правда есть проблемы, ну тогда не судьба, пока не добавят поддержку :–)

**Comment by Krekotun** [comment]
Я смотрел в сторону posthtml
У него есть подобный синтаксис и еще полно плагинов.
Только неясно состояние проекта

**Comment by Krekotun** [comment]
Вполне возможно, этот вариант намного круче самого pug в долгосрочной перспективе.
Интересно было бы производительность как-то измерить.
