### ISSUE TITLE
Pug → Nunjucks

### ISSUE THREAD

**Issue by straykov** [straykov/initium#31]
Pug бесит отступами. Хочется чего-то больше похожего на HTML. Например, https://mozilla.github.io/nunjucks/

**Comment by gunlinux** [comment]
Pug и правда своеобразный, но предупрежу, что nunjucks - это вдохновление от jinja2, когда в последний раз воевал с jinja ним в попытках навести БЭМ, какая-то дичь получилась.

То есть для вещей сложнее layout/include/export/for/if/data он превращается в мутанта, но проще jade

**Comment by artshkurenko** [comment]
Твиг?

**Comment by straykov** [comment]
Переехали на Твиг
