### ISSUE TITLE
outline: none

### ISSUE THREAD

**Issue by pepelsbey** [straykov/initium#32]
Ну раз комментарии [в блоге Страйко́ва отключены](http://straykov.ru/blog/all/outline-none/), то давайте поговорим здесь. Решение проблемы «я написал у себя в блоге, а значит все это прочтут» немного наивное, вам не кажется?

Посмотрите на эту форму на сайте Ру-Центра:

![image](https://cloud.githubusercontent.com/assets/105274/21740814/43e15bb4-d4d6-11e6-84c2-363ade1da491.png)

Как думаете, где я сейчас нахожусь? В первом селекте, во втором, на первой или второй кнопке? Да где угодно — всё выглядит одинаково. А если у меня ещё зрение _чуть-чуть_ плохое, то я не увижу и мигающего курсора в полях.

Эти ребята не читали блог Страйко́ва. Они конечно и Инитум не использовали, но по всем признакам — как будто использовали.

А теперь посмотрите на форму, где я это пишу:

![image](https://cloud.githubusercontent.com/assets/105274/21740822/a48cd61e-d4d6-11e6-8a02-e7d91e30df61.png)

Ужасно? Да нет, нормально. Зато я знаю, что этот элемент активен и одной кнопкой я могу его активировать. Но ниже другой пример, кастомный аутлайн под кнопкой:

![image](https://cloud.githubusercontent.com/assets/105274/21740832/d5bbf512-d4d6-11e6-947f-22039bc4a1e2.png)

А под ней кнопка без аутлайна:

![image](https://cloud.githubusercontent.com/assets/105274/21740846/0ba3f5a8-d4d7-11e6-98dc-1e334d6e8a65.png)

Разницы почти нет — верстальщик подумал «да норм, и так понятно». Но нет, не понятно.

К чему я? Всё просто: не провоцируйте разработчиков делать плохие вещи. Лучше обидно спотыкаться каждый раз перед ямой и вспоминать, чем ровно в неё падать снова и снова.

**Comment by pepelsbey** [comment]
Чтиво:
- [Reset Revisited](http://meyerweb.com/eric/thoughts/2011/01/03/reset-revisited/)
- [`a { outline: none; }` DON'T DO IT!](http://www.outlinenone.com/)

**Comment by iegorov** [comment]
Дефолтный outline тоже ведь не всегда хорошо читается и не факт, что он будет лучше кастомного - это про зеленую кнопку.
В целом конечно согласен, что лучше базовый оставить, чем ожидать, что все свой реализуют.
Хотя тут вопрос уже ответственности, если внутри команды можно быть уверенным, что все хорошо, то при массовом использовании незнакомыми людьми такой уверенности быть не может.

p.s. Каждый не реализованный outline будет на вашей совести ... - шутка )

**Comment by sashasushko** [comment]
Я предпочитаю выключать, когда стилизовал. Такая себе изящная деградация на случай, если пропустил что.

> К чему я?
@pepelsbey, а не из мухи ли мы слона делаем?

**Comment by straykov** [comment]
На самом деле, ребята, доступность же не только про аутлайн. Этот тредик — хороший повод пойти и разобраться в ней подробнее.

**Comment by pepelsbey** [comment]
@sashasushko, я две ссылки дал выше, там очень подробно говорится о важности аутлайна для слабовидящих (то есть и нас с вами лет за 40). Не кажется ли это мухой из-за профдеформации, когда соответствие макету считается более важным, чем удобство использования?

**Comment by straykov** [comment]
@pepelsbey ну ты так говоришь про соответствие макету, как будто это что-то плохое. Дизайн может быть таким, что аутлайн просто будет не видно. У хорошего дизайнера макет содержит состояние — тогда следовать ему полезнее, чем надеяться на аутлайн

**Comment by pepelsbey** [comment]
Не плохое, менее важное, чем UX.

Есть состояние в макете? Отключи аутлайн и сделай состояние.
Нет состояния? Верстай дальше и не трогай аутлайн.

Вроде просто.

**Comment by disablesilence** [comment]
@straykov 

> В собственных проектах или в Кодельной мы никогда не выпустим формы без состояний. К большому сожалению, не все такие внимательные, как мы.

Ребят, вы сами об это спотыкаетесь. Первый сайт из портфолио: https://journal.tinkoff.ru/ — нереально использовать с клавиатуры, в виду отсутствия аутлайна.

К тому же Илья пишет в блоге, что аутлайн существует только как напоминание. Ну пусть будет напоминанием. Как сделал свой хороший аутлайн — отключил браузерный ручками.

**Comment by sashasushko** [comment]
> Не кажется ли это мухой из-за профдеформации...

@pepelsbey, я неверно выразился. Про муху к тому, где это мы обсуждаем.

Инитум — продукт с конкретными целями. Если в Кодельной никогда не сделают сайт без кастомных фокус-состояний, стоит ли им править свой шаблон, только потому что какой-нибудь Вася возьмёт его, а про замену `outline: none;` не подумает.

А вот где-нибудь на круглом столе после конференции я бы с удовольствием поддержал вашу сторону о необходимости `outline` и не только ;-)

**Comment by pepelsbey** [comment]
> Стоит ли им править свой шаблон, потому что какой-нибудь Вася…

Стоит. Код — это граната. Когда она в руках профессионала — всё в порядке. Когда она в опенсорсе — лучше бы ей быть с чекой. Вопрос ответственности за публичные действия.

**Comment by zamkevich** [comment]
Давно пользуюсь такой штукой: https://github.com/wilddeer/focus-fix
Вот для размышления: http://wd.dizaina.net/internet-maintenance/on-outlines/

**Comment by pepelsbey** [comment]
Какое-то странное желание контролировать вид и поведение интерфейса на 100%, чтобы ни пунктирчика не пролезно, ни мошки, ни блошки. Невозможно это, какие нормалайзы ни прикручивай, какими JS ни вмешивайся в клики — браузеры всё равно сделают как удобно пользователям.

Когда я читаю «бесит аутлайн», я слышу «это не по макету! не трогайте мою вёрстку, проклятые пользователи, просто смотрите».

**Comment by straykov** [comment]
> браузеры всё равно сделают как удобно пользователям

Браузеры сделают как-то, как по мнению ребят правильно, это не значит, что обязательно будет удобно пользователям

**Comment by zamkevich** [comment]
Я думаю что логично для начала разделить проблему на две сущности:
**Первая** это поведение аутлайна. Аутлайн не должен появляться везде где ты кликнул мышкой. Это тупой подход. Браузеры его реализуют потому, что в виду зоопарка технологий они не могут угадать где в вашем интерфейсе должно быть выделение при клике. И они никогда не смогут это сделать. Поэтому для начала научитесь отключать выделение там, где оно не нужно. Посмотрите как это делают ребята из эппла у себя на сайте. 

**Вторая сущность** — визуальная. Синяя рамка не назойливый элемент. Когда решена первая сущность, то вторая уже почти не раздражает.  Если по задумке подсветка фокуса должна выглядеть иначе — просто сделайте как нужно. Тупо ждать от браузера, что он угадает ваши пожелания на конкретном проекте. 

**Отдельно о слабовидящих** 
Этим ребятам глубоко до одного места все холивары на их счёт. Они давно пользуется расширениями или специальными продуктам облегчающими работу с любыми сайтами. 
Меня очень веселит когда по закону нужно делать версию сайта для слабовидящих — вот интересно как слабовидящий должен по мнению законников узнать где заветная кнопка переключения в «его» режим и есть ли она вообще?

**Comment by straykov** [comment]
@pepelsbey спешу сообщить, что аутлайн снова на месте
